/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

char *__cdecl _Enct(LPCSTR lpString); // idb
char *__cdecl _Dect(char *); // idb
char *__cdecl _Dect1(char *); // idb
void __cdecl _E2(); // idb
char *__cdecl _Dect2(char *); // idb
void __cdecl _E4(); // idb
char *__cdecl stristr(char *Source, const char *); // idb
unsigned __int16 *__cdecl wcsistr(wchar_t *, wchar_t *String); // idb
// int __stdcall lstrlenA(LPCSTR lpString);
// void __stdcall LeaveCriticalSection(LPCRITICAL_SECTION lpCriticalSection);
// LPSTR __stdcall lstrcpyA(LPSTR lpString1, LPCSTR lpString2);
// DWORD __stdcall GetCurrentThreadId();
// void __stdcall EnterCriticalSection(LPCRITICAL_SECTION lpCriticalSection);
// int __cdecl atexit(void (__cdecl *)());
// void __stdcall InitializeCriticalSection(LPCRITICAL_SECTION lpCriticalSection);
// void __stdcall DeleteCriticalSection(LPCRITICAL_SECTION lpCriticalSection);
// void __cdecl free(void *Block);
// char *__cdecl strstr(const char *Str, const char *SubStr);
// char *__cdecl _strlwr(char *String);
// char *__cdecl _strdup(const char *Source);
// wchar_t *__cdecl wcsstr(const wchar_t *Str, const wchar_t *SubStr);
// wchar_t *__cdecl _wcslwr(wchar_t *String);
// wchar_t *__cdecl _wcsdup(const wchar_t *String);
// size_t __cdecl wcslen(const wchar_t *String);

//-------------------------------------------------------------------------
// Data declarations

struct _RTL_CRITICAL_SECTION _cs__1___Dect1__YAPADPAD_Z_4VCCriticalSector__A; // idb
int _dwLastTid__1___Dect1__YAPADPAD_Z_4PAKA[]; // weak
_UNKNOWN unk_1C; // weak
int _lpszLast__1___Dect1__YAPADPAD_Z_4PAPADA[10]; // idb
struct _RTL_CRITICAL_SECTION _cs__1___Dect2__YAPADPAD_Z_4VCCriticalSector__A; // idb
char __S1__1___Dect1__YAPADPAD_Z_4EA; // weak
char __S3__1___Dect2__YAPADPAD_Z_4EA; // weak
LPCSTR _lpszLast__1___Dect2__YAPADPAD_Z_4PADA; // idb
char _buf__1___Enct__YAPADPAD_Z_4PADA[]; // weak
char byte_89; // weak
char byte_8A; // weak
char byte_8B; // weak
_UNKNOWN unk_8C; // weak
int _dwLastIndex__1___Dect1__YAPADPAD_Z_4KA; // weak


//----- (000004A4) --------------------------------------------------------
char *__cdecl _Enct(LPCSTR lpString)
{
  int v2; // eax
  int v3; // esi
  int v4; // ecx
  char v5; // dl
  int v6; // ecx
  int v7; // edi
  int v8; // ebp
  int v9; // ecx
  char lpStringa; // [esp+8h] [ebp+4h]

  v2 = lstrlenA(lpString);
  if ( !v2 )
    return _buf__1___Enct__YAPADPAD_Z_4PADA;
  byte_89 = (char)lpString;
  _buf__1___Enct__YAPADPAD_Z_4PADA[0] = 1;
  lpStringa = 3 * (_BYTE)lpString + 101;
  v3 = 4;
  v4 = 3 * (3 * (unsigned __int8)lpString + 1);
  v5 = v4 + 101;
  v6 = v4 + 1;
  if ( v2 > 0 )
  {
    v7 = lpString - (LPCSTR)&unk_8C;
    v8 = v2;
    do
    {
      v9 = 3 * v6;
      _buf__1___Enct__YAPADPAD_Z_4PADA[v3] = (v9 + 101) ^ _buf__1___Enct__YAPADPAD_Z_4PADA[v7 + v3];
      ++v3;
      v6 = v9 + 1;
      --v8;
    }
    while ( v8 );
  }
  _buf__1___Enct__YAPADPAD_Z_4PADA[v3] = 0;
  byte_8A = lpStringa ^ ((unsigned __int16)(v3 - 4) >> 8);
  byte_8B = (v3 - 4) ^ v5;
  return _buf__1___Enct__YAPADPAD_Z_4PADA;
}
// 89: using guessed type char byte_89;
// 8A: using guessed type char byte_8A;
// 8B: using guessed type char byte_8B;

//----- (00000544) --------------------------------------------------------
char *__cdecl _Dect(char *a1)
{
  char *result; // eax
  int v2; // ecx
  int v3; // esi
  char v4; // bl
  int v5; // ecx
  unsigned __int16 v6; // dx
  int v7; // ecx
  char v8; // bl

  result = a1;
  if ( a1 && *a1 == 1 )
  {
    v2 = 9 * a1[1] + 3;
    a1[2] ^= 3 * a1[1] + 0x65;
    v3 = 0;
    v4 = (v2 + 0x65) ^ a1[3];
    HIBYTE(v6) = a1[2];
    v5 = v2 + 1;
    LOBYTE(v6) = v4;
    a1[3] = v4;
    if ( v6 )
    {
      do
      {
        v7 = 3 * v5;
        v8 = (v7 + 0x65) ^ a1[v3 + 4];
        v5 = v7 + 1;
        a1[v3++] = v8;
      }
      while ( v3 < v6 );
    }
    a1[v6] = 0;
  }
  return result;
}

//----- (000005B4) --------------------------------------------------------
char *__cdecl _Dect1(char *a1)
{
  char v2; // bl
  int v3; // esi
  int v4; // eax
  unsigned __int16 v5; // cx
  char v6; // bl
  int v7; // eax
  int v8; // ebp
  int v9; // eax
  char v10; // cl
  int v11; // ebx
  DWORD v12; // eax
  int v13; // edx
  _DWORD *v14; // ecx
  int v15; // esi
  int v16; // eax
  char v17; // sp
  int v18; // ecx
  int v19; // ebp
  int v20; // edx
  int v21; // ecx
  char v22; // bl
  int i; // ecx
  int v24; // ecx
  char v25; // [esp+Ch] [ebp-408h]
  CHAR String1[1024]; // [esp+14h] [ebp-400h] BYREF

  if ( (__S1__1___Dect1__YAPADPAD_Z_4EA & 1) == 0 )
  {
    __S1__1___Dect1__YAPADPAD_Z_4EA |= 1u;
    InitializeCriticalSection(&_cs__1___Dect1__YAPADPAD_Z_4VCCriticalSector__A);
    atexit(_E2);
  }
  if ( !a1 )
    return 0;
  EnterCriticalSection(&_cs__1___Dect1__YAPADPAD_Z_4VCCriticalSector__A);
  if ( *a1 == 1 )
  {
    v2 = a1[3];
    v3 = 0;
    v4 = 9 * a1[1] + 3;
    a1[2] ^= 3 * a1[1] + 0x65;
    HIBYTE(v5) = a1[2];
    v6 = (v4 + 0x65) ^ v2;
    v7 = v4 + 1;
    LOBYTE(v5) = v6;
    a1[3] = v6;
    v8 = v5;
    if ( v5 )
    {
      do
      {
        v9 = 3 * v7;
        v10 = (v9 + 0x65) ^ a1[v3 + 4];
        v7 = v9 + 1;
        a1[v3++] = v10;
      }
      while ( v3 < v8 );
    }
    a1[v8] = 0;
  }
  v11 = 0;
  v12 = GetCurrentThreadId();
  v13 = 1;
  v14 = &unk_1C;
  while ( *v14 != v12 )
  {
    ++v14;
    ++v13;
    if ( (int)v14 >= (int)_lpszLast__1___Dect1__YAPADPAD_Z_4PAPADA )
      goto LABEL_14;
  }
  v11 = v13;
  if ( v13 )
    goto LABEL_16;
LABEL_14:
  if ( (unsigned int)_dwLastIndex__1___Dect1__YAPADPAD_Z_4KA < 9 )
  {
    v11 = ++_dwLastIndex__1___Dect1__YAPADPAD_Z_4KA;
    _dwLastTid__1___Dect1__YAPADPAD_Z_4PAKA[_dwLastIndex__1___Dect1__YAPADPAD_Z_4KA] = v12;
  }
LABEL_16:
  v15 = _lpszLast__1___Dect1__YAPADPAD_Z_4PAPADA[v11];
  _lpszLast__1___Dect1__YAPADPAD_Z_4PAPADA[v11] = (int)a1;
  if ( v15 )
  {
    if ( (char *)v15 != a1 && *a1 != 1 && *(_BYTE *)v15 != 1 )
    {
      lstrcpyA(String1, (LPCSTR)v15);
      v16 = lstrlenA(String1);
      if ( v16 )
      {
        *(_BYTE *)v15 = 1;
        v18 = (unsigned __int8)(v17 + 28);
        v19 = 4;
        *(_BYTE *)(v15 + 1) = v18;
        v25 = 3 * v18 + 0x65;
        v20 = 0;
        v21 = 3 * (3 * v18 + 1);
        v22 = v21 + 0x65;
        for ( i = v21 + 1; v20 < v16; ++v20 )
        {
          v24 = 3 * i;
          *(_BYTE *)(v15 + v19++) = (v24 + 0x65) ^ String1[v20];
          i = v24 + 1;
        }
        *(_BYTE *)(v15 + v19) = 0;
        *(_BYTE *)(v15 + 2) = v25 ^ ((unsigned __int16)(v19 - 4) >> 8);
        *(_BYTE *)(v15 + 3) = (v19 - 4) ^ v22;
      }
    }
  }
  LeaveCriticalSection(&_cs__1___Dect1__YAPADPAD_Z_4VCCriticalSector__A);
  return a1;
}
// 6FB: variable 'v17' is possibly undefined
// 18: using guessed type int _dwLastTid__1___Dect1__YAPADPAD_Z_4PAKA[];
// 80: using guessed type char __S1__1___Dect1__YAPADPAD_Z_4EA;
// 488: using guessed type int _dwLastIndex__1___Dect1__YAPADPAD_Z_4KA;

//----- (00000784) --------------------------------------------------------
void __cdecl _E2()
{
  DeleteCriticalSection(&_cs__1___Dect1__YAPADPAD_Z_4VCCriticalSector__A);
}

//----- (00000794) --------------------------------------------------------
char *__cdecl _Dect2(char *a1)
{
  int v2; // edi
  int v3; // eax
  char v4; // cl
  char v5; // cl
  int v6; // eax
  unsigned __int16 v7; // cx
  int v8; // ebp
  int v9; // eax
  char v10; // cl
  CHAR *v11; // edi
  int v12; // eax
  char v13; // sp
  int v14; // ecx
  int v15; // ebp
  int v16; // edx
  int v17; // ecx
  char v18; // bl
  int i; // ecx
  int v20; // ecx
  char v21; // [esp+Ch] [ebp-408h]
  CHAR String1[1024]; // [esp+14h] [ebp-400h] BYREF

  if ( (__S3__1___Dect2__YAPADPAD_Z_4EA & 1) == 0 )
  {
    __S3__1___Dect2__YAPADPAD_Z_4EA |= 1u;
    InitializeCriticalSection(&_cs__1___Dect2__YAPADPAD_Z_4VCCriticalSector__A);
    atexit(_E4);
  }
  if ( !a1 )
    return 0;
  EnterCriticalSection(&_cs__1___Dect2__YAPADPAD_Z_4VCCriticalSector__A);
  if ( *a1 == 1 )
  {
    v2 = 0;
    v3 = 9 * a1[1] + 3;
    v4 = a1[3];
    a1[2] ^= 3 * a1[1] + 101;
    v5 = (v3 + 101) ^ v4;
    v6 = v3 + 1;
    a1[3] = v5;
    HIBYTE(v7) = a1[2];
    LOBYTE(v7) = a1[3];
    v8 = v7;
    if ( v7 )
    {
      do
      {
        v9 = 3 * v6;
        v10 = (v9 + 101) ^ a1[v2 + 4];
        v6 = v9 + 1;
        a1[v2++] = v10;
      }
      while ( v2 < v8 );
    }
    a1[v8] = 0;
  }
  v11 = (CHAR *)_lpszLast__1___Dect2__YAPADPAD_Z_4PADA;
  _lpszLast__1___Dect2__YAPADPAD_Z_4PADA = a1;
  if ( v11 )
  {
    if ( v11 != a1 && *a1 != 1 && *v11 != 1 )
    {
      lstrcpyA(String1, v11);
      v12 = lstrlenA(String1);
      if ( v12 )
      {
        *v11 = 1;
        v14 = (unsigned __int8)(v13 + 28);
        v15 = 4;
        v11[1] = v14;
        v21 = 3 * v14 + 101;
        v16 = 0;
        v17 = 3 * (3 * v14 + 1);
        v18 = v17 + 101;
        for ( i = v17 + 1; v16 < v12; ++v16 )
        {
          v20 = 3 * i;
          v11[v15++] = (v20 + 101) ^ String1[v16];
          i = v20 + 1;
        }
        v11[v15] = 0;
        v11[2] = v21 ^ ((unsigned __int16)(v15 - 4) >> 8);
        v11[3] = (v15 - 4) ^ v18;
      }
    }
  }
  LeaveCriticalSection(&_cs__1___Dect2__YAPADPAD_Z_4VCCriticalSector__A);
  return a1;
}
// 88F: variable 'v13' is possibly undefined
// 81: using guessed type char __S3__1___Dect2__YAPADPAD_Z_4EA;

//----- (00000914) --------------------------------------------------------
void __cdecl _E4()
{
  DeleteCriticalSection(&_cs__1___Dect2__YAPADPAD_Z_4VCCriticalSector__A);
}

//----- (00000924) --------------------------------------------------------
char *__cdecl stristr(char *Source, const char *a2)
{
  char *v2; // eax
  char *v3; // esi
  char *v4; // eax
  char *v5; // eax
  char *v6; // edi
  char *v7; // eax
  char *v8; // ebx
  char *result; // eax

  if ( !Source || !a2 || !strlen(a2) )
    return Source;
  v2 = _strdup(Source);
  v3 = _strlwr(v2);
  v4 = _strdup(a2);
  v5 = _strlwr(v4);
  v6 = v5;
  if ( v3 && v5 )
  {
    v7 = strstr(v3, v5);
    v8 = v7;
    if ( v7 )
      v8 = &v7[Source - v3];
    free(v3);
    free(v6);
    result = v8;
  }
  else
  {
    free(v3);
    free(v6);
    result = 0;
  }
  return result;
}

//----- (000009B4) --------------------------------------------------------
unsigned __int16 *__cdecl wcsistr(wchar_t *a1, wchar_t *String)
{
  wchar_t *v2; // eax
  wchar_t *v3; // esi
  wchar_t *v4; // eax
  wchar_t *v5; // eax
  wchar_t *v6; // ebx
  wchar_t *v7; // eax
  unsigned __int16 *v8; // edi
  unsigned __int16 *result; // eax

  if ( !a1 || !String || !wcslen(String) )
    return a1;
  v2 = _wcsdup(a1);
  v3 = _wcslwr(v2);
  v4 = _wcsdup(String);
  v5 = _wcslwr(v4);
  v6 = v5;
  if ( v3 && v5 )
  {
    v7 = wcsstr(v3, v5);
    v8 = v7;
    if ( v7 )
      v8 = &a1[v7 - v3];
    free(v3);
    free(v6);
    result = v8;
  }
  else
  {
    free(v3);
    free(v6);
    result = 0;
  }
  return result;
}

// nfuncs=24 queued=8 decompiled=8 lumina nreq=0 worse=0 better=0
// ALL OK, 8 function(s) have been successfully decompiled
