/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int __cdecl MemGetPrivateProfileInt(const char *a1, const char *a2, int a3, char *a4);
unsigned int __cdecl MemGetPrivateProfileString(const char *, const char *, const char *Source, char *Dest, size_t Count, char *); // idb
char *__cdecl GetLine(char *a1, _BYTE *a2);
int __cdecl MemGetPrivateProfileSectionNames(char *Dest, unsigned int a2, char *a3);
// int sscanf(const char *const Buffer, const char *const Format, ...);
// int sprintf(char *const Buffer, const char *const Format, ...);
// unsigned __int8 *__cdecl _mbsnbcpy(unsigned __int8 *Dest, const unsigned __int8 *Source, size_t Count);
// int __cdecl _mbsnbicmp(const unsigned __int8 *Str1, const unsigned __int8 *Str2, size_t MaxCount);
// unsigned __int8 *__cdecl _mbsnbcat(unsigned __int8 *Dest, const unsigned __int8 *Source, size_t Count);
// unsigned __int8 *__cdecl _mbsrchr(const unsigned __int8 *String, unsigned int C);


//----- (00000000) --------------------------------------------------------
int __cdecl MemGetPrivateProfileInt(const char *a1, const char *a2, int a3, char *a4)
{
  int v5; // [esp+0h] [ebp-84h] BYREF
  char Buffer[64]; // [esp+4h] [ebp-80h] BYREF
  char Dest[64]; // [esp+44h] [ebp-40h] BYREF

  sprintf(Buffer, "%ld", a3);
  MemGetPrivateProfileString(a1, a2, Buffer, Dest, 0x40u, a4);
  v5 = 0;
  sscanf(Dest, "%ld", &v5);
  return v5;
}

//----- (00000074) --------------------------------------------------------
unsigned int __cdecl MemGetPrivateProfileString(const char *a1, const char *a2, const char *Source, char *Dest, size_t Count, char *a6)
{
  size_t v6; // ebp
  unsigned int v7; // kr08_4
  char *v8; // esi
  char *v9; // esi
  size_t v10; // esi
  const char *v11; // edx
  const unsigned __int8 *v13; // [esp-8h] [ebp-194h]
  size_t v14; // [esp-4h] [ebp-190h]
  char v15[64]; // [esp+Ch] [ebp-180h] BYREF
  char Buffer[64]; // [esp+4Ch] [ebp-140h] BYREF
  unsigned __int8 Str2[256]; // [esp+8Ch] [ebp-100h] BYREF

  sprintf(Buffer, "[%s]", a1);
  sprintf(v15, "%s=", a2);
  v6 = strlen(Buffer);
  v7 = strlen(v15) + 1;
  v8 = GetLine(a6, Str2);
  if ( _mbsnbicmp((const unsigned __int8 *)Buffer, Str2, v6) )
  {
    while ( *v8 )
    {
      v8 = GetLine(v8, Str2);
      if ( !_mbsnbicmp((const unsigned __int8 *)Buffer, Str2, v6) )
        goto LABEL_4;
    }
    v10 = Count;
    v11 = Source;
    v14 = Count;
    goto LABEL_11;
  }
LABEL_4:
  v9 = GetLine(v8, Str2);
  if ( Str2[0] != 91 )
  {
    while ( _mbsnbicmp((const unsigned __int8 *)v15, Str2, v7 - 1) )
    {
      if ( *v9 )
      {
        v9 = GetLine(v9, Str2);
        if ( Str2[0] != 91 )
          continue;
      }
      goto LABEL_8;
    }
    v10 = Count;
    v14 = Count;
    v11 = (const char *)&Str2[strlen(v15)];
LABEL_11:
    v13 = (const unsigned __int8 *)v11;
    goto LABEL_12;
  }
LABEL_8:
  v10 = Count;
  v14 = Count;
  v13 = (const unsigned __int8 *)Source;
LABEL_12:
  _mbsnbcpy((unsigned __int8 *)Dest, v13, v14);
  Dest[v10 - 1] = 0;
  return strlen(Dest);
}

//----- (00000200) --------------------------------------------------------
char *__cdecl GetLine(char *a1, _BYTE *a2)
{
  char *result; // eax
  int v3; // edx
  char i; // cl

  result = a1;
  v3 = 0;
  for ( i = *a1; *result; i = *result )
  {
    if ( i == '\r' )
      break;
    if ( i == '\n' )
      break;
    *a2++ = i;
    ++result;
    if ( ++v3 >= 255 )
      break;
  }
  *a2 = 0;
  if ( *result == '\r' )
    ++result;
  if ( *result == '\n' )
    ++result;
  return result;
}

//----- (00000250) --------------------------------------------------------
int __cdecl MemGetPrivateProfileSectionNames(char *Dest, unsigned int a2, char *a3)
{
  unsigned __int8 *v4; // ebp
  unsigned __int8 *v5; // eax
  unsigned int v6; // kr04_4
  size_t v7; // esi
  unsigned __int8 *v8; // ebp
  int v9; // ebp
  int result; // eax
  unsigned __int8 String; // [esp+10h] [ebp-100h] BYREF
  unsigned __int8 Source[255]; // [esp+11h] [ebp-FFh] BYREF

  v4 = (unsigned __int8 *)Dest;
  *Dest = 0;
  do
  {
    a3 = GetLine(a3, &String);
    if ( String == 91 )
    {
      v5 = _mbsrchr(&String, ']');
      if ( v5 )
      {
        *v5 = 0;
        v6 = strlen((const char *)Source) + 1;
        v7 = v6 - 1;
        if ( a2 < v6 + 1 )
          v7 = a2 - 2;
        _mbsnbcat(v4, Source, v7);
        v8 = &v4[v7];
        *v8 = 0;
        a2 += -1 - v7;
        v4 = v8 + 1;
        if ( a2 <= 1 )
          break;
      }
    }
  }
  while ( *a3 );
  *v4 = 0;
  v9 = v4 - (unsigned __int8 *)Dest;
  result = v9;
  if ( v9 > 0 )
    result = v9 - 1;
  return result;
}

// nfuncs=10 queued=4 decompiled=4 lumina nreq=0 worse=0 better=0
// ALL OK, 4 function(s) have been successfully decompiled
