/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void __cdecl RC4_set_key(struct rc4_key_st *, int, unsigned __int8 *); // idb
void __cdecl RC4(struct rc4_key_st *, unsigned int, unsigned __int8 *, unsigned __int8 *); // idb

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN loc_3E; // weak


//----- (00000000) --------------------------------------------------------
void __cdecl RC4_set_key(struct rc4_key_st *a1, int a2, unsigned __int8 *a3)
{
  char *v3; // esi
  char v4; // di
  unsigned int v5; // eax
  _DWORD *v6; // ecx
  int v7; // eax
  int *v8; // ecx
  int v9; // edx
  int v10; // ebx
  int v11; // eax
  int v12; // edx
  int v13; // ebx
  int v14; // eax
  int v15; // edx
  int v16; // ebx
  int v17; // eax
  int v18; // edx
  int v19; // ebx
  struct rc4_key_st *v20; // [esp+14h] [ebp+4h]

  v3 = (char *)a1 + 8;
  v4 = 0;
  v5 = 0;
  v6 = (_DWORD *)((char *)a1 + 8);
  do
    *v6++ = v5++;
  while ( v5 < 0x100 );
  *(_DWORD *)a1 = 0;
  *((_DWORD *)a1 + 1) = 0;
  v7 = 0;
  v8 = (int *)((char *)a1 + 16);
  v20 = (struct rc4_key_st *)(&loc_3E + 2);
  do
  {
    v9 = *(v8 - 2);
    v10 = (unsigned __int8)(v4 + v9 + a3[v7]);
    v11 = v7 + 1;
    if ( v11 == a2 )
      v11 = 0;
    *(v8 - 2) = *(_DWORD *)&v3[4 * v10];
    *(_DWORD *)&v3[4 * v10] = v9;
    v12 = *(v8 - 1);
    v13 = (unsigned __int8)(v10 + v12 + a3[v11]);
    v14 = v11 + 1;
    if ( v14 == a2 )
      v14 = 0;
    *(v8 - 1) = *(_DWORD *)&v3[4 * v13];
    *(_DWORD *)&v3[4 * v13] = v12;
    v15 = *v8;
    v16 = (unsigned __int8)(v13 + *v8 + a3[v14]);
    v17 = v14 + 1;
    if ( v17 == a2 )
      v17 = 0;
    *v8 = *(_DWORD *)&v3[4 * v16];
    *(_DWORD *)&v3[4 * v16] = v15;
    v18 = v8[1];
    v19 = (unsigned __int8)(v16 + v18 + a3[v17]);
    v7 = v17 + 1;
    v4 = v19;
    if ( v7 == a2 )
      v7 = 0;
    v8[1] = *(_DWORD *)&v3[4 * v19];
    *(_DWORD *)&v3[4 * v19] = v18;
    v8 += 4;
    v20 = (struct rc4_key_st *)((char *)v20 - 1);
  }
  while ( v20 );
}

//----- (000000F0) --------------------------------------------------------
void __cdecl RC4(struct rc4_key_st *a1, unsigned int a2, unsigned __int8 *a3, unsigned __int8 *a4)
{
  char v4; // dl
  int v6; // ebp
  int v7; // edi
  int v8; // edi
  int v9; // ecx
  int v10; // ebp
  int v11; // edx
  int v12; // edi
  int v13; // edx
  int v14; // ebp
  int v15; // ebx
  int v16; // edi
  int v17; // edx
  int v18; // ebp
  int v19; // ebx
  int v20; // edi
  int v21; // edx
  int v22; // ebp
  int v23; // ebx
  int v24; // edi
  int v25; // edx
  int v26; // ebp
  int v27; // ebx
  int v28; // edi
  int v29; // edx
  int v30; // ebp
  int v31; // ebx
  int v32; // edi
  int v33; // edx
  int v34; // ebp
  int v35; // ebx
  int v36; // edx
  int v37; // ebx
  unsigned __int8 *v38; // ecx
  unsigned __int8 *v39; // esi
  int v40; // edi
  int v41; // edx
  int v42; // ebp
  int v43; // ebx
  _BYTE *v44; // ecx
  _BYTE *v45; // esi
  int v46; // edi
  int v47; // edx
  int v48; // ebp
  int v49; // ebx
  int v50; // edi
  int v51; // edx
  int v52; // ebp
  int v53; // ebx
  int v54; // edi
  int v55; // edx
  int v56; // ebp
  int v57; // ebx
  int v58; // edi
  int v59; // edx
  int v60; // ebp
  int v61; // ebx
  int v62; // edi
  int v63; // edx
  int v64; // ebp
  int v65; // ebx
  int v66; // edi
  int v67; // edx
  int v68; // ebp
  int v69; // ebx
  int v70; // edx
  int v71; // ebx
  int v72; // edx
  int v73; // ebx
  _BYTE *v74; // ecx
  _BYTE *v75; // esi
  int v76; // edx
  int v77; // ebx
  _BYTE *v78; // ecx
  _BYTE *v79; // esi
  int v80; // edx
  int v81; // ebx
  _BYTE *v82; // ecx
  _BYTE *v83; // esi
  int v84; // edx
  int v85; // ebx
  _BYTE *v86; // ecx
  _BYTE *v87; // esi
  int v88; // edx
  int v89; // ebx
  _BYTE *v90; // ecx
  _BYTE *v91; // esi
  int v92; // edx
  int v93; // ebx
  _BYTE *v94; // ecx
  _BYTE *v95; // esi
  int v96; // edx
  int v97; // ebx
  _BYTE *v98; // ecx
  _BYTE *v99; // esi
  int v100; // edx
  int v101; // ebx
  struct rc4_key_st *v102; // [esp+14h] [ebp+4h]
  struct rc4_key_st *v103; // [esp+14h] [ebp+4h]
  struct rc4_key_st *i; // [esp+14h] [ebp+4h]
  struct rc4_key_st *v105; // [esp+14h] [ebp+4h]
  struct rc4_key_st *v106; // [esp+14h] [ebp+4h]
  struct rc4_key_st *v107; // [esp+14h] [ebp+4h]
  struct rc4_key_st *v108; // [esp+14h] [ebp+4h]
  struct rc4_key_st *v109; // [esp+14h] [ebp+4h]
  struct rc4_key_st *v110; // [esp+14h] [ebp+4h]
  unsigned __int8 *v111; // [esp+20h] [ebp+10h]

  v4 = a2;
  v6 = *((_DWORD *)a1 + 1);
  v7 = *(_DWORD *)a1;
  v102 = (struct rc4_key_st *)(a2 >> 3);
  if ( a2 >> 3 )
  {
    v8 = (unsigned __int8)(v7 + 1);
    v9 = *((_DWORD *)a1 + v8 + 2);
    v10 = (unsigned __int8)(v9 + v6);
    v11 = *((_DWORD *)a1 + v10 + 2);
    *((_DWORD *)a1 + v8 + 2) = v11;
    *((_DWORD *)a1 + v10 + 2) = v9;
    *a4 = *a3 ^ *((_BYTE *)a1 + 4 * (unsigned __int8)(v9 + v11) + 8);
    v12 = (unsigned __int8)(v8 + 1);
    v13 = *((_DWORD *)a1 + v12 + 2);
    v14 = (unsigned __int8)(v13 + v10);
    v15 = *((_DWORD *)a1 + v14 + 2);
    *((_DWORD *)a1 + v12 + 2) = v15;
    *((_DWORD *)a1 + v14 + 2) = v13;
    a4[1] = a3[1] ^ *((_BYTE *)a1 + 4 * (unsigned __int8)(v13 + v15) + 8);
    v16 = (unsigned __int8)(v12 + 1);
    v17 = *((_DWORD *)a1 + v16 + 2);
    v18 = (unsigned __int8)(v17 + v14);
    v19 = *((_DWORD *)a1 + v18 + 2);
    *((_DWORD *)a1 + v16 + 2) = v19;
    *((_DWORD *)a1 + v18 + 2) = v17;
    a4[2] = a3[2] ^ *((_BYTE *)a1 + 4 * (unsigned __int8)(v17 + v19) + 8);
    v20 = (unsigned __int8)(v16 + 1);
    v21 = *((_DWORD *)a1 + v20 + 2);
    v22 = (unsigned __int8)(v21 + v18);
    v23 = *((_DWORD *)a1 + v22 + 2);
    *((_DWORD *)a1 + v20 + 2) = v23;
    *((_DWORD *)a1 + v22 + 2) = v21;
    a4[3] = a3[3] ^ *((_BYTE *)a1 + 4 * (unsigned __int8)(v21 + v23) + 8);
    v24 = (unsigned __int8)(v20 + 1);
    v25 = *((_DWORD *)a1 + v24 + 2);
    v26 = (unsigned __int8)(v25 + v22);
    v27 = *((_DWORD *)a1 + v26 + 2);
    *((_DWORD *)a1 + v24 + 2) = v27;
    *((_DWORD *)a1 + v26 + 2) = v25;
    a4[4] = a3[4] ^ *((_BYTE *)a1 + 4 * (unsigned __int8)(v25 + v27) + 8);
    v28 = (unsigned __int8)(v24 + 1);
    v29 = *((_DWORD *)a1 + v28 + 2);
    v30 = (unsigned __int8)(v29 + v26);
    v31 = *((_DWORD *)a1 + v30 + 2);
    *((_DWORD *)a1 + v28 + 2) = v31;
    *((_DWORD *)a1 + v30 + 2) = v29;
    a4[5] = a3[5] ^ *((_BYTE *)a1 + 4 * (unsigned __int8)(v29 + v31) + 8);
    v32 = (unsigned __int8)(v28 + 1);
    v33 = *((_DWORD *)a1 + v32 + 2);
    v34 = (unsigned __int8)(v33 + v30);
    v35 = *((_DWORD *)a1 + v34 + 2);
    *((_DWORD *)a1 + v32 + 2) = v35;
    *((_DWORD *)a1 + v34 + 2) = v33;
    a4[6] = a3[6] ^ *((_BYTE *)a1 + 4 * (unsigned __int8)(v33 + v35) + 8);
    v7 = (unsigned __int8)(v32 + 1);
    v36 = *((_DWORD *)a1 + v7 + 2);
    v6 = (unsigned __int8)(v36 + v34);
    v37 = *((_DWORD *)a1 + v6 + 2);
    *((_DWORD *)a1 + v7 + 2) = v37;
    *((_DWORD *)a1 + v6 + 2) = v36;
    a4[7] = a3[7] ^ *((_BYTE *)a1 + 4 * (unsigned __int8)(v36 + v37) + 8);
    v38 = a4 + 8;
    v39 = a3 + 8;
    if ( v102 != (struct rc4_key_st *)((char *)RC4_set_key + 1) )
    {
      v111 = (unsigned __int8 *)v102 - 1;
      do
      {
        v40 = (unsigned __int8)(v7 + 1);
        v41 = *((_DWORD *)a1 + v40 + 2);
        v42 = (unsigned __int8)(v41 + v6);
        v43 = *((_DWORD *)a1 + v42 + 2);
        *((_DWORD *)a1 + v40 + 2) = v43;
        *((_DWORD *)a1 + v42 + 2) = v41;
        *v38 = *v39 ^ *((_BYTE *)a1 + 4 * (unsigned __int8)(v41 + v43) + 8);
        v44 = v38 + 1;
        v45 = v39 + 1;
        v46 = (unsigned __int8)(v40 + 1);
        v47 = *((_DWORD *)a1 + v46 + 2);
        v48 = (unsigned __int8)(v47 + v42);
        v49 = *((_DWORD *)a1 + v48 + 2);
        *((_DWORD *)a1 + v46 + 2) = v49;
        *((_DWORD *)a1 + v48 + 2) = v47;
        *v44++ = *v45++ ^ *((_BYTE *)a1 + 4 * (unsigned __int8)(v47 + v49) + 8);
        v50 = (unsigned __int8)(v46 + 1);
        v51 = *((_DWORD *)a1 + v50 + 2);
        v52 = (unsigned __int8)(v51 + v48);
        v53 = *((_DWORD *)a1 + v52 + 2);
        *((_DWORD *)a1 + v50 + 2) = v53;
        *((_DWORD *)a1 + v52 + 2) = v51;
        *v44++ = *v45++ ^ *((_BYTE *)a1 + 4 * (unsigned __int8)(v51 + v53) + 8);
        v54 = (unsigned __int8)(v50 + 1);
        v55 = *((_DWORD *)a1 + v54 + 2);
        v56 = (unsigned __int8)(v55 + v52);
        v57 = *((_DWORD *)a1 + v56 + 2);
        *((_DWORD *)a1 + v54 + 2) = v57;
        *((_DWORD *)a1 + v56 + 2) = v55;
        *v44++ = *v45++ ^ *((_BYTE *)a1 + 4 * (unsigned __int8)(v55 + v57) + 8);
        v58 = (unsigned __int8)(v54 + 1);
        v59 = *((_DWORD *)a1 + v58 + 2);
        v60 = (unsigned __int8)(v59 + v56);
        v61 = *((_DWORD *)a1 + v60 + 2);
        *((_DWORD *)a1 + v58 + 2) = v61;
        *((_DWORD *)a1 + v60 + 2) = v59;
        *v44++ = *v45++ ^ *((_BYTE *)a1 + 4 * (unsigned __int8)(v59 + v61) + 8);
        v62 = (unsigned __int8)(v58 + 1);
        v63 = *((_DWORD *)a1 + v62 + 2);
        v64 = (unsigned __int8)(v63 + v60);
        v65 = *((_DWORD *)a1 + v64 + 2);
        *((_DWORD *)a1 + v62 + 2) = v65;
        *((_DWORD *)a1 + v64 + 2) = v63;
        *v44++ = *v45++ ^ *((_BYTE *)a1 + 4 * (unsigned __int8)(v63 + v65) + 8);
        v66 = (unsigned __int8)(v62 + 1);
        v67 = *((_DWORD *)a1 + v66 + 2);
        v68 = (unsigned __int8)(v67 + v64);
        v69 = *((_DWORD *)a1 + v68 + 2);
        *((_DWORD *)a1 + v66 + 2) = v69;
        *((_DWORD *)a1 + v68 + 2) = v67;
        *v44++ = *v45++ ^ *((_BYTE *)a1 + 4 * (unsigned __int8)(v67 + v69) + 8);
        v7 = (unsigned __int8)(v66 + 1);
        v70 = *((_DWORD *)a1 + v7 + 2);
        v6 = (unsigned __int8)(v70 + v68);
        v71 = *((_DWORD *)a1 + v6 + 2);
        *((_DWORD *)a1 + v7 + 2) = v71;
        *((_DWORD *)a1 + v6 + 2) = v70;
        *v44 = *v45 ^ *((_BYTE *)a1 + 4 * (unsigned __int8)(v70 + v71) + 8);
        v38 = v44 + 1;
        v39 = v45 + 1;
        --v111;
      }
      while ( v111 );
    }
    v4 = a2;
  }
  else
  {
    v38 = a4;
    v39 = a3;
  }
  v103 = (struct rc4_key_st *)(v4 & 7);
  if ( (v4 & 7) != 0 )
  {
    v7 = (unsigned __int8)(v7 + 1);
    v72 = *((_DWORD *)a1 + v7 + 2);
    v6 = (unsigned __int8)(v72 + v6);
    v73 = *((_DWORD *)a1 + v6 + 2);
    *((_DWORD *)a1 + v7 + 2) = v73;
    *((_DWORD *)a1 + v6 + 2) = v72;
    *v38 = *v39 ^ *((_BYTE *)a1 + 4 * (unsigned __int8)(v72 + v73) + 8);
    v74 = v38 + 1;
    v75 = v39 + 1;
    for ( i = (struct rc4_key_st *)((char *)v103 - 1); i; i = (struct rc4_key_st *)((char *)v110 - 1) )
    {
      v7 = (unsigned __int8)(v7 + 1);
      v76 = *((_DWORD *)a1 + v7 + 2);
      v6 = (unsigned __int8)(v76 + v6);
      v77 = *((_DWORD *)a1 + v6 + 2);
      *((_DWORD *)a1 + v7 + 2) = v77;
      *((_DWORD *)a1 + v6 + 2) = v76;
      *v74 = *v75 ^ *((_BYTE *)a1 + 4 * (unsigned __int8)(v76 + v77) + 8);
      v78 = v74 + 1;
      v79 = v75 + 1;
      v105 = (struct rc4_key_st *)((char *)i - 1);
      if ( !v105 )
        break;
      v7 = (unsigned __int8)(v7 + 1);
      v80 = *((_DWORD *)a1 + v7 + 2);
      v6 = (unsigned __int8)(v80 + v6);
      v81 = *((_DWORD *)a1 + v6 + 2);
      *((_DWORD *)a1 + v7 + 2) = v81;
      *((_DWORD *)a1 + v6 + 2) = v80;
      *v78 = *v79 ^ *((_BYTE *)a1 + 4 * (unsigned __int8)(v80 + v81) + 8);
      v82 = v78 + 1;
      v83 = v79 + 1;
      v106 = (struct rc4_key_st *)((char *)v105 - 1);
      if ( !v106 )
        break;
      v7 = (unsigned __int8)(v7 + 1);
      v84 = *((_DWORD *)a1 + v7 + 2);
      v6 = (unsigned __int8)(v84 + v6);
      v85 = *((_DWORD *)a1 + v6 + 2);
      *((_DWORD *)a1 + v7 + 2) = v85;
      *((_DWORD *)a1 + v6 + 2) = v84;
      *v82 = *v83 ^ *((_BYTE *)a1 + 4 * (unsigned __int8)(v84 + v85) + 8);
      v86 = v82 + 1;
      v87 = v83 + 1;
      v107 = (struct rc4_key_st *)((char *)v106 - 1);
      if ( !v107 )
        break;
      v7 = (unsigned __int8)(v7 + 1);
      v88 = *((_DWORD *)a1 + v7 + 2);
      v6 = (unsigned __int8)(v88 + v6);
      v89 = *((_DWORD *)a1 + v6 + 2);
      *((_DWORD *)a1 + v7 + 2) = v89;
      *((_DWORD *)a1 + v6 + 2) = v88;
      *v86 = *v87 ^ *((_BYTE *)a1 + 4 * (unsigned __int8)(v88 + v89) + 8);
      v90 = v86 + 1;
      v91 = v87 + 1;
      v108 = (struct rc4_key_st *)((char *)v107 - 1);
      if ( !v108 )
        break;
      v7 = (unsigned __int8)(v7 + 1);
      v92 = *((_DWORD *)a1 + v7 + 2);
      v6 = (unsigned __int8)(v92 + v6);
      v93 = *((_DWORD *)a1 + v6 + 2);
      *((_DWORD *)a1 + v7 + 2) = v93;
      *((_DWORD *)a1 + v6 + 2) = v92;
      *v90 = *v91 ^ *((_BYTE *)a1 + 4 * (unsigned __int8)(v92 + v93) + 8);
      v94 = v90 + 1;
      v95 = v91 + 1;
      v109 = (struct rc4_key_st *)((char *)v108 - 1);
      if ( !v109 )
        break;
      v7 = (unsigned __int8)(v7 + 1);
      v96 = *((_DWORD *)a1 + v7 + 2);
      v6 = (unsigned __int8)(v96 + v6);
      v97 = *((_DWORD *)a1 + v6 + 2);
      *((_DWORD *)a1 + v7 + 2) = v97;
      *((_DWORD *)a1 + v6 + 2) = v96;
      *v94 = *v95 ^ *((_BYTE *)a1 + 4 * (unsigned __int8)(v96 + v97) + 8);
      v98 = v94 + 1;
      v99 = v95 + 1;
      v110 = (struct rc4_key_st *)((char *)v109 - 1);
      if ( !v110 )
        break;
      v7 = (unsigned __int8)(v7 + 1);
      v100 = *((_DWORD *)a1 + v7 + 2);
      v6 = (unsigned __int8)(v100 + v6);
      v101 = *((_DWORD *)a1 + v6 + 2);
      *((_DWORD *)a1 + v7 + 2) = v101;
      *((_DWORD *)a1 + v6 + 2) = v100;
      *v98 = *v99 ^ *((_BYTE *)a1 + 4 * (unsigned __int8)(v100 + v101) + 8);
      v74 = v98 + 1;
      v75 = v99 + 1;
    }
  }
  *(_DWORD *)a1 = v7;
  *((_DWORD *)a1 + 1) = v6;
}

// nfuncs=2 queued=2 decompiled=2 lumina nreq=0 worse=0 better=0
// ALL OK, 2 function(s) have been successfully decompiled
